### ISSUE TITLE
Feedback to Milestone 3

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/noRmtest#30]
- The branch coverage needs to be 100%, if your package is impossible to achieve 100%, please explain the reason.
- Please don't use the attached image for usage example, this is user unfriendly. (User prefer copy paste sample code!)
- For installation instruction, add this: "Install devtools from CRAN install.packages("devtools", build_vignettes = TRUE),In an R environment, load devtools library(devtools)". devtools are required for installation, but the user might not know.
- Please add the screenshot when you passed all test case and package installation, in case my library or program backend does not work appropriately.

**Comment by Doooooris** [comment]
- Missing vignette, please add it and ensure it is built next time. You can found more information on slack

**Comment by rzitomer** [comment]
Thanks for the feedback! Below we've listed our updates based on your feedback.

- We've updated tests so coverage is now 100%
- We've updated the readme to have text usage examples, and just have pictures of the output
- We've added to the installation instructions how to install and load devtools as suggested
- We've updated the screenshot to show all test cases passed and theres full branch coverage
- We've added a working vignette
